version: "3"
services:
  qr-service-1:
    build:
      context: .
      dockerfile: Dockerfile.qr
    environment:
      - PORT=3001
      - SERVER_URL=http://190.181.22.187:3001/api/token
    ports:
      - "3001:3001"
    volumes:
      - ./sessions/qr-service-1:/app/sessions

  qr-service-2:
    build:
      context: .
      dockerfile: Dockerfile.qr
    environment:
      - PORT=3002
      - SERVER_URL=http://190.181.22.187:3001/api/token
    ports:
      - "3002:3002"
    volumes:
      - ./sessions/qr-service-2:/app/sessions

  qr-service-3:
    build:
      context: .
      dockerfile: Dockerfile.qr
    environment:
      - PORT=3003
      - SERVER_URL=http://190.181.22.187:3001/api/token
    ports:
      - "3003:3003"
    volumes:
      - ./sessions/qr-service-3:/app/sessions

  qr-service-4:
    build:
      context: .
      dockerfile: Dockerfile.qr
    environment:
      - PORT=3004
      - SERVER_URL=http://190.181.22.187:3001/api/token
    ports:
      - "3004:3004"
    volumes:
      - ./sessions/qr-service-4:/app/sessions