version: "3"
services:
  qr-service:
    build:
      context: .
      dockerfile: Dockerfile.qr
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.wwebjs_cache:/app/.wwebjs_cache
    ports:
      - "3001:3000"

  token-service:
    build:
      context: .
      dockerfile: Dockerfile.token
    ports:
      - "3000:3000"
