version: "3"
services:
  qr-service:
    build:
      context: .
      dockerfile: Dockerfile.qr
    environment:
      - PORT=${PORT:-3001}
      - SERVER_URL=${SERVER_URL:-http://dashboard.pasantia.com/api/token}
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
