version: "3"
services:
  qr-service:
    build:
      context: .
      dockerfile: Dockerfile.qr

    ports:
      - "3001:3000"

  token-service:
    build:
      context: .
      dockerfile: Dockerfile.token
    ports:
      - "3800:3800"
